export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";


export const UPDATE_CONTROL_QUEUES = "UPDATE_CONTROL_QUEUES";
export const UPDATE_VIEWERS = "UPDATE_VIEWERS";
export const UPDATE_WAITLISTS = "UPDATE_WAITLISTS";

export const UPDATE_TURN_EXPIRATIONS = "UPDATE_TURN_EXPIRATIONS";
export const UPDATE_TURN_LENGTHS = "UPDATE_TURN_LENGTHS";

export const UPDATE_VOLUME = "UPDATE_VOLUME";

// user info:
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const CHANGE_USERNAME = "CHANGE_USERNAME";

export const RECEIVE_USERNAME_MAP = "RECEIVE_USERNAME_MAP";
export const RECEIVE_ACCOUNT_MAP = "RECEIVE_ACCOUNT_MAP";

export const UPDATE_CONTROLLER_STATE = "UPDATE_CONTROLLER_STATE";

export const UPDATE_SETTINGS = "UPDATE_SETTINGS";

// players:
export const UPDATE_PLAYER_CONTROL_QUEUES = "UPDATE_PLAYER_CONTROL_QUEUES";
export const UPDATE_PLAYER_TURN_START_TIMES = "UPDATE_PLAYER_TURN_START_TIMES";
export const UPDATE_PLAYER_TURN_LENGTHS = "UPDATE_PLAYER_TURN_LENGTHS";
export const UPDATE_PLAYER_CONTROLLER_STATE = "UPDATE_PLAYER_CONTROLLER_STATE";

export const JOIN_PLAYER_CONTROL_QUEUE = "JOIN_PLAYER_CONTROL_QUEUE";
export const LEAVE_PLAYER_CONTROL_QUEUE = "LEAVE_PLAYER_CONTROL_QUEUE";

// time:
export const UPDATE_SERVER_TIME = "UPDATE_SERVER_TIME";
export const UPDATE_LAST_SERVER_UPDATE = "UPDATE_LAST_SERVER_UPDATE";
export const UPDATE_PING = "UPDATE_PING";
