export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";


export const UPDATE_CONTROL_QUEUES = "UPDATE_CONTROL_QUEUES";
export const UPDATE_VIEWERS = "UPDATE_VIEWERS";
export const UPDATE_WAITLISTS = "UPDATE_WAITLISTS";

export const UPDATE_TURN_EXPIRATIONS = "UPDATE_TURN_EXPIRATIONS";
export const UPDATE_TURN_LENGTHS = "UPDATE_TURN_LENGTHS";

export const UPDATE_VOLUME = "UPDATE_VOLUME";


export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const CHANGE_USERNAME = "CHANGE_USERNAME";

export const RECEIVE_USERNAME_MAP = "RECEIVE_USERNAME_MAP";

export const UPDATE_CONTROLLER_STATE = "UPDATE_CONTROLLER_STATE";


export const UPDATE_SETTINGS = "UPDATE_SETTINGS";